openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://vcloud.dev.comciencia.cl/bb/

info:
  description: |
    ## Info ##
    API that allows interfacing of a Keycloak User Storage SPI with the Benutzer table of S-Verein. 
    Make sure to always view the model and not just the examples, because the models contain a lot of important descriptions for
    the fields that are otherwise not visible in Swagger.
    
    See the GIT readme.md file for further information.

  version: "1.0.0"
  title: verein.cloud BB API
  contact:
    email: mheumann@comciencia.cl
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /deliver-client-creds:
    post:
      summary: Receives client credentials for the specified club, so that communication with the BB API is possible.
      operationId: deliverClientCreds
      description: |
        Called by BB after a successful login with the credentials needed for talking to the BuchhaltungsButler API.
      parameters:
        - in: query
          name: vid
          description: Vereins ID, corresponds to club shortkey.
          required: true
          schema:
            type: string
            maxLength: 50
        - in: query
          name: bbCustId
          description: Customer ID on BuchhaltungsButler side
          required: true
          schema:
            type: string
            maxLength: 50
        - in: query
          name: bbUserId
          description: User ID on BuchhaltungsButler side
          required: false
          schema:
            type: string
            maxLength: 50
        - in: query
          name: vvUsername
          description: Username of this user on VV side for correct assignment of bbUserId. Required if bbUserId is set.
          required: false
          schema:
            type: string
            maxLength: 50
        - in: query
          name: apiClient
          description: API Client for communication with BB API
          required: true
          schema:
            type: string
            maxLength: 100
        - in: query
          name: apiSecret
          description: API Secret for communication with BB API
          required: true
          schema:
            type: string
            maxLength: 255
        - in: query
          name: apiKey
          description: API Key for communication with BB API
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        '200':
          description: Data stored successfully
        '400':
          description: Bad or invalid input parameter
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        "405":
          description: Invalid vid, db connection not possible
        '500':
          description: Database error when writing data

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    ForbiddenError:
      description: Trying to access a resource that is not allowed for this user

security:
  - bearerAuth: []
