  /deliver-client-creds:
    post:
      summary: Receives client credentials for the specified club, so that communication with the BB API is possible.
      operationId: deliverClientCreds
      description: |
        Called by BB after a successful login with the credentials needed for talking to the BuchhaltungsButler API.
      parameters:
        - in: query
          name: vid
          description: Vereins ID, corresponds to club shortkey.
          required: true
          schema:
            type: string
            maxLength: 50
        - in: query
          name: bbCustId
          description: Customer ID on BuchhaltungsButler side
          required: true
          schema:
            type: string
            maxLength: 50
        - in: query
          name: bbUserId
          description: User ID on BuchhaltungsButler side
          required: false
          schema:
            type: string
            maxLength: 50
        - in: query
          name: vvUsername
          description: Username of this user on VV side for correct assignment of bbUserId. Required if bbUserId is set.
          required: false
          schema:
            type: string
            maxLength: 50
        - in: query
          name: apiClient
          description: API Client for communication with BB API
          required: true
          schema:
            type: string
            maxLength: 100
        - in: query
          name: apiSecret
          description: API Secret for communication with BB API
          required: true
          schema:
            type: string
            maxLength: 255
        - in: query
          name: apiKey
          description: API Key for communication with BB API
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        '200':
          description: Data stored successfully
        '400':
          description: Bad or invalid input parameter
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        "405":
          description: Invalid vid, db connection not possible
        '500':
          description: Database error when writing data
